import { FaRegHandPaper } from "react-icons/fa";
import { FiUpload } from "react-icons/fi";
import { PiCurrencyGbp } from "react-icons/pi";

const inventoryData = [
  {
    id: 1,
    ticketType: "General Admission",
    quantity: 5,
    splitType: "None",
    seatingArrangement: "Reserved Seating",
    maxDisplayQuantity: 10,
    fanArea: "Home Fans",
    category: "Home Fans Section",
    sectionBlock: "Longside Lower Tier",
    row: 12,
    firstSeat: 24,
    faceValue: 7500,
    payoutPrice: 7000,
    benefits: "None",
    restrictions: "No Alcohol",
    dateToShip: "15/11/2023",
    ticketsInHand: true,
    uploadTickets: null,
    leftIcon: PiCurrencyGbp,
    uploadIcon: FiUpload,
    handIcon: FaRegHandPaper
  },
  {
    id: 2,
    ticketType: "VIP",
    quantity: 2,
    splitType: "Not Seated Together",
    seatingArrangement: "Box Seats",
    maxDisplayQuantity: null,
    fanArea: "Premium Lounge",
    category: "Premium",
    sectionBlock: "Center Box",
    row: 3,
    firstSeat: 5,
    faceValue: 45000,
    payoutPrice: 42000,
    benefits: "Meet & Greet",
    restrictions: "Dress Code",
    dateToShip: "10/12/2023",
    ticketsInHand: false,
    uploadTickets: "vip_tickets.pdf",
    leftIcon: PiCurrencyGbp,
    uploadIcon: FiUpload,
    handIcon: FaRegHandPaper
  },
  {
    id: 3,
    ticketType: "Student",
    quantity: 1,
    splitType: "None",
    seatingArrangement: "General Admission",
    maxDisplayQuantity: 25,
    fanArea: null,
    category: "Neutral Zone",
    sectionBlock: null,
    row: null,
    firstSeat: null,
    faceValue: 3500,
    payoutPrice: 3000,
    benefits: "None",
    restrictions: "Age Restricted",
    dateToShip: "20/11/2023",
    ticketsInHand: true,
    uploadTickets: null,
    leftIcon: PiCurrencyGbp,
    uploadIcon: FiUpload,
    handIcon: FaRegHandPaper
  },
  // Continue with 47 more items in the same format...
  {
    id: 50,
    ticketType: "Season Pass",
    quantity: 1,
    splitType: "None",
    seatingArrangement: "Reserved Seating",
    maxDisplayQuantity: null,
    fanArea: "Home Fans",
    category: "Home Fans Section",
    sectionBlock: "Longside Upper Tier",
    row: 8,
    firstSeat: 15,
    faceValue: 90000,
    payoutPrice: 85000,
    benefits: "Merchandise Pack",
    restrictions: "None",
    dateToShip: "01/12/2023",
    ticketsInHand: true,
    uploadTickets: "season_pass.pdf",
    leftIcon: PiCurrencyGbp,
    uploadIcon: FiUpload,
    handIcon: FaRegHandPaper
  }
];

export default inventoryData;